# Site settings
title: Casey's Technobabble
email: 
description: > # this means to ignore newlines until "baseurl:"
  Feel free to contact me.  The opinions on this site do not 
  reflect the opinions of my employer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caseylmanus.github.io" # the base hostname & protocol for your site
twitter_username: caseymanus
github_username:  caseylmanus

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day